[book]
title = "Manual de ReferÃªncia da ğŸ”° NeoBASIC 4GL"
description = "A Linguagem de ProgramaÃ§Ã£o NeoBASIC"
language = "pt"
src = "src"
authors = [
  "Raul Bras",
  "ContribuiÃ§Ãµes da Comunidade NeoBASIC"
]
